config/routes.rb
PolestarAstrology::Application.routes.draw do
  resources :star_groups
  
  resources :comments

  resources :chart_palaces do
    resources :star_relationships
    resources :comments
  end

  resources :articles

  resources :charts, controller: 'people', as: 'people' do
    # resource :chart, :only => :show
    resources :palaces, controller: 'chart_palaces', as: 'chart_palaces', only: [:show], key: :foobax
  end
  
  get '/tong_shu/week/(:week)' => 'tong_shus#week_of', :as => 'tong_shu_week'
  get '/tong_shu/:year/:month' => 'tong_shus#index', :as => 'tong_shu_index'
  
  resources :feedback, controller: 'feedbacks', as: 'feedbacks'
  resources :tong_shus
  
  resources :stars, :only => [:index, :show] do
    resources :comments
  end
  
  resources :star_palaces do
    resources :comments
  end
  
  resources :branches, :only => [:index, :show] do
    resources :comments
  end
  
  resources :elements, :only => [:index, :show] do
    resources :comments
  end
  
  resources :stems_and_branches, controller: 'pillars', as: 'pillars', :only => [:index, :show] do
    resources :comments
  end
  
  resources :lunar_dates, only: [:show], format: :json
  
  resources :search, only: [:index, :create]
  
  resources :star_relationships do
    resources :comments
  end
  
  resources :palaces do
    resources :star_relationships do
      put :sort, on: :collection
    end
    get 'by_star/:star_id', :action => :show, :on => :member
  end
  
  namespace :admin do
    resources :members
  end

  devise_for :members
  
  devise_scope :member do
    get "sign_out", :to => "devise/sessions#destroy"
  end  
  
  resources :passwords, :only => [:edit, :update], controller: 'change_passwords'
  get '/change_password' => 'change_passwords#edit', :as => :change_password
  get '/updates' => 'articles#index', :as => :blog

  root :to => 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  extend FriendlyId
  friendly_id :full_name, use: [:finders, :slugged]
  belongs_to :member
  belongs_to :chart
  
  default_scope ->{order(:last_name, :first_name)}
  
  before_validation do
    puts self.year.inspect
    
    if dob_changed? || year_branch_id.nil? || hour_branch_id.nil?
      self.chart = Chart.find_or_create(dob)
      self.year_branch_id = chart.year.branch_id
      self.hour_branch_id = chart.hour.branch_id
    end
  end
  
  def year_branch
    @year_branch ||= Branch.find(year_branch_id)
  end

  def hour_branch
    @hour_branch ||= Branch.find(hour_branch_id)
  end
    
  # validates :year, numericality: { :greater_than_or_equal_to => 1900, :less_than_or_equal_to => 2099 }
  # validates :month, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 12 }
  # validates :day, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 31 }
  
  validates :dob, :presence => true
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def year
    dob.year if dob
  end
  
  def month
    dob.month if dob
  end
  
  def day
    dob.day if dob
  end
  
  def time
    dob
  end
    
  def chart
    if super.nil?
      update_attributes chart: Chart.find_or_create(dob)
    end
    super
  end
  
  MONTHS = [['January', 1], ['February', 2], ['March', 3], ['April', 4], ['May', 5], ['June', 6], ['July', 7], ['August', 8], ['September', 9], ['October', 10], ['November', 11], ['December', 12]]
end

app/controllers/people_controller.rb
# encoding: utf-8
class PeopleController < ApplicationController
  before_action :authenticate_member!, :load_member

  respond_to :html, :json
  # before_filter :replace_date_parts_with_date_time
  
  def index
    @people = current_member.people
    
    if params[:term]
      @people = @people.select{|t| t.full_name.downcase.index(params[:term].downcase)}
    else
      @people = @people.page(params[:page])
    end

    respond_with(@people) do |format|
      format.json {
        render json: @people.map{|p|
          {name: p.full_name, value: person_path(p)}
        }
      }
    end
  end

  def show
    @person = Person.find(params[:id])
    if params[:id].match(/^\d+$/) || params[:id].match(/^[a-zA-Z\-]+\d*$/)
      unless resource.chart
        resource.update_attributes chart: Chart.find_or_create(resource.dob)
      end
      @chart = resource.chart
      @name  = resource.full_name
    else
      @chart = Chart.find_or_create(DateTime.parse(params[:id]))
    end
    
    if params[:year]
      puts params[:year].inspect
      ming_branch = Branch.by_name(params[:year])
      # @ages = @chart.palaces.by_location(Branch.by_name(params[:year])).great_limit(@chart, @person)
      
      #  ok need to reset the order.
      #  go through the chart_palaces.
      #  whatever is the current Branch of the palace,
      #  Its new branch will be the Ming branch added to the 

      @chart.palaces.sort{|t, u| t.location.ordinal <=> u.location.ordinal}.each_with_index do |chart_palace, i|
        chart_palace.palace = Palace[((chart_palace.palace.id + ming_branch.ordinal - @chart.ming_id - 1) % 12) + 1]
      end
    end
    
    # Load a list of star relationships for this chart
    @relationships = {}

    if params[:decade]
      ming_branch = Branch.by_name(params[:decade])
      @ages = @chart.palaces.by_location(Branch.by_name(params[:decade])).great_limit(@chart, @person)
      
      #  ok need to reset the order.
      #  go through the chart_palaces.
      #  whatever is the current Branch of the palace,
      #  Its new branch will be the Ming branch added to the 

      @chart.palaces.sort{|t, u| t.location.ordinal <=> u.location.ordinal}.each_with_index do |chart_palace, i|
        chart_palace.palace = Palace[((chart_palace.palace.id + ming_branch.ordinal - @chart.ming_id - 1) % 12) + 1]
      end
    end
    
    @chart.palaces.each do |palace|
      @relationships[palace.palace] = palace.my_star_relationships(current_member)
    end
    
    @crack_addict = %(<!-- start slipsum code -->
    You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, <br/><hr/><br/> but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.

    <!-- please do not remove this line -->

    <div style="display:none;">
    <a href="http://slipsum.com">lorem ipsum</a></div>

    <!-- end slipsum code -->
    )
    
    respond_to do |format|
      format.html
      # format.html { render :layout => 'chart' }
      format.pdf {
        pdf = ChartPdf.new(@chart, @name, view_context)
        send_data pdf.render, filename: "chart_#{@name}.pdf", type: "application/pdf", disposition: 'inline'
      }
    end
  end
  
  def create
    @person = current_member.people.build person_params
    @person.dob = get_time_from_params
    @person.save
    
    respond_with @person
  end
  
  def get_time_from_params
    year = params[:person][:year]
    month = params[:person][:month]
    day = params[:person][:day]
    time = params[:person][:time]
    DateTime.parse("#{year}-#{month}-#{day} #{time}")
  end
  
  def update
    @person = Person.find params[:id]
    authorize! :manage, @person
    puts "Setting time: #{get_time_from_params.inspect}"
    @person.attributes = person_params
    @person.dob = get_time_from_params
    @person.save
    
    respond_with @person
  end
  
  def edit
    @person = Person.find(params[:id])
    respond_with @person
  end
  
  def new
    @person = current_member.people.build
    respond_with resource
  end
  
  def destroy
    person = Person.find(params[:id])
    authorize! :manage, person
    person.destroy
    respond_with person
  end

  protected
  def person_params
    params[:person].permit(:first_name, :last_name, :yin_yang)
  end
  
  def load_member
    @member = current_member
  end
  
  def replace_date_parts_with_date_time
    if params[:person] && params[:person]['dob(1i)']
      p = params[:person]
      dob = DateTime.parse("#{p['dob(1i)']}/#{p['dob(2i)']}/#{p['dob(3i)']} #{p['dob(4i)']}:#{p['dob(5i)']}")
      p.delete_if{|t,u| t.match /dob/}
      p['dob'] = dob
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def palace_animal_display(chart_palace)
    [chart_palace.location.char, chart_palace.location.pinyin, chart_palace.location.animal].join(' ')
  end
  
  def borrowed_stars(palace)
    @chart.palaces[palace.location.diametric].major_stars.sort_by_rank
  end
  
  def major_stars(palace)
    palace.major_stars.sort_by_rank
  end
  
  def minor_stars(palace)
    palace.minor_stars.sort_by_rank
  end
  
  def comments_for_star_in_chart_palace(star, chart_palace)
    chart_palace.my_star_relationships(current_member, star).map{|star_relationship|
      
    }
  end
end

app/views/people/_animal.html.haml
.animal{class: animal}
  = link_to branch_path(animal) do
    = image_tag "animals/#{animal}.png"

app/views/people/_chart_analysis_accordion.html.haml
.chart_analysis_accordion
  %h3= link_to 'Four Pillars Analysis', '#'
  .analyzing_four_pillars
    %h3 Analyzing the Four Pillars:
    %ol
      %li 
        %p
          The Earthly Branch of the Year is #{@chart.year.branch.animal.titleize}.
          = render :partial => 'show_comments', :object => @chart.year.branch
            
      %li
        %p
          The Heavenly Stem of the Year is #{@chart.year.stem.name}.  How does this relate to the Earthly Branch?
          %ul.list_stuff
            %li
              The native element of #{@chart.year.branch.animal.titleize} is #{@chart.year.native_element.name.titleize}.
              #{@chart.year.native_element.related_to(Element.by_name(@chart.year.stem.element))}.
          = render :partial => 'show_comments', :object => @chart.year.stem._element
          = render :partial => 'show_comments', :object => @chart.year
      %li 
        %p 
          The Earthly Branch of the Hour is #{@chart.hour.branch.animal.titleize}.
          = render :partial => 'show_comments', :object => @chart.hour.branch
      %li
        %p
          The Heavenly Stem of the Hour is #{@chart.hour.stem.name}.  How does this relate to the Earthly Branch?
          %ul.list_stuff
            %li
              The native element of #{@chart.hour.branch.animal.titleize} is #{@chart.hour.native_element.name.titleize}.
              #{@chart.hour.native_element.related_to(Element.by_name(@chart.hour.stem.element))}.
          = render :partial => 'show_comments', :object => @chart.hour.stem._element
          = render :partial => 'show_comments', :object => @chart.hour
      %li 
        %p Now synthesize a picture of the character based on these four steps, remembering the precedence of the first ones over the later ones.
    .inner_to_outer
      %h3 
        Inner Element (#{@chart.inner_element.titleize}) and Year Stem (#{@chart.year.stem.element.titleize}):
        #{Element.by_name(@chart.year.stem.element).related_to(Element.by_name(@chart.inner_element))}
  - @chart.palaces.each do |chart_palace|
    %h3= link_to chart_palace.palace.name, '#'
    .chart_palace
      - chart_palace.stars.each do |star|
        .chart_palace_star
          %h4= star.pinyin
          - star.my_comments(current_member).each do |comment|
            .comment!= RedCloth.new(comment.comments).to_html
          - star.star_palace(chart_palace.palace).my_comments(current_member).each do |comment|
            .comment!= RedCloth.new(comment.comments).to_html

app/views/people/_chart_analysis_tabs.html.haml
#chart_analysis_tabs.tab-pane.active
  %ul#palace_tabs.nav.nav-tabs
    %li.active= link_to 'Pillars', '#tab_pillars', data: {toggle: 'tab'}
    - Palace.all.each do |palace|
      %li= link_to palace.name, "#tab_#{palace.friendly_id}", data: {toggle: 'tab'}
  .tab-content
    #tab_pillars.tab-pane.active
      %h3 Analyzing the Four Pillars:
      %ol
        %li 
          %p
            The Earthly Branch of the Year is #{@chart.year.branch.animal.titleize}.
            = render :partial => 'show_comments', :object => @chart.year.branch
        %li
          %p
            The Heavenly Stem of the Year is #{@chart.year.stem.name}.  How does this relate to the Earthly Branch?
            %ul.list_stuff
              %li
                The native element of #{@chart.year.branch.animal.titleize} is #{@chart.year.native_element.name.titleize}.
                #{@chart.year.native_element.related_to(Element.by_name(@chart.year.stem.element))}.
            = render :partial => 'show_comments', :object => @chart.year.stem._element
            = render :partial => 'show_comments', :object => @chart.year
        %li 
          %p 
            The Earthly Branch of the Hour is #{@chart.hour.branch.animal.titleize}.
            = render :partial => 'show_comments', :object => @chart.hour.branch
        %li
          %p
            The Heavenly Stem of the Hour is #{@chart.hour.stem.name}.  How does this relate to the Earthly Branch?
            %ul.list_stuff
              %li
                The native element of #{@chart.hour.branch.animal.titleize} is #{@chart.hour.native_element.name.titleize}.
                #{@chart.hour.native_element.related_to(Element.by_name(@chart.hour.stem.element))}.
            = render :partial => 'show_comments', :object => @chart.hour.stem._element
            = render :partial => 'show_comments', :object => @chart.hour
        %li 
          %p Now synthesize a picture of the character based on these four steps, remembering the precedence of the first ones over the later ones.
      .inner_to_outer
        %h3 
          Inner Element (#{@chart.inner_element.titleize}) and Year Stem (#{@chart.year.stem.element.titleize}):
          #{Element.by_name(@chart.year.stem.element).related_to(Element.by_name(@chart.inner_element))}
    - @chart.palaces.each do |chart_palace|
      .chart_palace.tab-pane{id: "tab_#{chart_palace.palace.friendly_id}"}
        %h1= chart_palace.palace.name
        - if chart_palace.major_stars.empty?
          - borrowed_stars(chart_palace).each do |star|
            %h3= link_to "(#{star.full_name})", star, target: '_blank'
        - chart_palace.stars.each do |star|
          %h3= link_to "#{star.full_name}", star, target: '_blank'
        %h3= link_to "#{chart_palace.palace.name} Palace in this chart", '#'
        = comment_box(chart_palace)
        - chart_palace.my_star_relationships(current_member).each do |star_relationship|
          %h3= link_to star_relationship_label(star_relationship), '#'
          = comment_box star_relationship

app/views/people/_chart_palace_star.html.haml
.chart_palace_star
  %h3= link_to 'General Info', '#'
  .general_info
    = comment_box(star)

  %h3= link_to "#{star.pinyin} in the #{chart_palace.palace.name} Palace", '#'
  .specific_info
    = comment_box(star.star_palace(chart_palace.palace)) if star.star_palace(chart_palace.palace)

app/views/people/_form.html.haml
= form_for @person do |f|
  -if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    %table
      %tr
        %td{colspan: 3}
          %h4 Name
      %tr
        %td= f.text_field :first_name, placeholder: 'First', class: 'input-medium', autocomplete: 'off'
        %td= f.text_field :last_name, placeholder: 'Last', class: 'input-medium', autocomplete: 'off'
        %td= f.select :yin_yang, [['Yin (Female)', 'yin'], ['Yang (Male)', 'yang']]
  .field
    %h4 Birth Date
    = f.text_field :year, placeholder: 'Year (4 digits)', class: 'input-small', autocomplete: 'off'
    = f.select :month, Person::MONTHS, class: 'input-small'
    = f.text_field :day, class: 'input-small', placeholder: 'Day', autocomplete: 'off'
    %span.input-append.bootstrap-timepicker
      = f.time_field :time, class: 'input-small', placeholder: '12:00 PM', autocomplete: 'off'
      %span.add-on
        %i.icon-time
    
  -# .field#timezone
  -#   = render 'timezone_thingy'
  
  .actions
    = f.submit 'Save'

app/views/people/_number.html.haml
!= 

app/views/people/_person.html.haml
%li[person]{data: {url: person_path(person)}}
  %span= person.full_name
  %span
    = render partial: 'animal', object: person.year_branch.animal
    = render partial: 'animal', object: person.hour_branch.animal

  %span.details.pull-right
    = link_to person_path(person.slug, format: :pdf), rel: 'tooltip', title: 'Download chart as PDF File' do
      %i.icon-download
    = link_to edit_person_path(person.slug), rel: 'tooltip', title: 'Make changes' do
      %i.icon-edit
    = link_to person_path(person), class: 'tooltippy', title: 'Remove', method: :delete, data: {:confirm => 'Really?'} do
      %i.icon-trash

app/views/people/_show_comments.html.haml
- unless (comments = Comment.comments_for(current_member, show_comments)).empty?
  %ul.list_stuff
    - comments.each do |comment|
      .comment!= RedCloth.new(comment.comments).to_html

app/views/people/_timezone_thingy.html.erb
<div id="timezone_select">
  <table>
    <tr>
      <td><h4>Region:</h4></td>
      <td><h4>Time Zone:</h4></td>
    </tr>
    <tr>
      <td><select name="region" id="region_select"></select></td>
      <td><select name="zone" id="zone_select"></select></td>
    </tr>
  </table>
</div>

app/views/people/blah.haml
.bs-docs-example
  %ul#myTab.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", :href => "#home"} Home
    %li
      %a{"data-toggle" => "tab", :href => "#profile"} Profile
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Dropdown
        %b.caret
      %ul.dropdown-menu
        %li
          %a{"data-toggle" => "tab", :href => "#dropdown1"} @fat
        %li
          %a{"data-toggle" => "tab", :href => "#dropdown2"} @mdo
  #myTabContent.tab-content
    #home.tab-pane.fade.in.active
      %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
    #profile.tab-pane.fade
      %p Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.
    #dropdown1.tab-pane.fade
      %p Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.
    #dropdown2.tab-pane.fade
      %p Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
.span6.charts_list
  %h3
    Saved Charts
  = link_to new_person_path, class: 'new_chart', rel: 'tooltip', title: 'Create a New Chart' do
    = image_tag 'icons/new_document.png'
  %ul.unstyled
    = render @people
  = paginate @people, :theme => 'twitter-bootstrap'
.span5
  %h3 Animals
  = render partial: 'animal', collection: Branch::ANIMALS

%br
- if @people.empty?
  %div{align: :center}
    %div Add people you know and their dates of birth.
    %div Click "View PDF Chart" to view the chart in your browser 
    %div (some browsers will just download the file).
    %div Click "Download PDF" to download the file to your computer.

app/views/people/new.html.haml
%h1 Create a New Chart

-# %h2= Time.zone

= render 'form'
= link_to 'Back', people_path

app/views/people/show.html.haml
.row#chart_container
  .chart.span9.well.well-small
    = render 'charts/title_info'
    = render partial: 'chart_palaces/chart_box', collection: @chart.palaces
  .span3.chart_details.well.well-small
    .shananana
      %ul.nav.nav-tabs.hide
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Choose a Palace
            %b.caret
          %ul.dropdown-menu#palace_selector
            - @chart.palaces.each do |chart_palace|
              %li
                %a{"data-toggle" => "tab", :href => "#chart_palace_#{chart_palace.id}"}= chart_palace.palace.name
      .tab-content
        - @chart.palaces.each do |chart_palace|
          .palace_details.tab-pane.fade[chart_palace]
            = render chart_palace
    

- if @person
  = content_for :main_nav do
    = icon_nav_link '', 'icon-print', '#', class: 'print'