config/routes.rb
PolestarAstrology::Application.routes.draw do
  resources :star_groups
  
  resources :comments

  resources :chart_palaces do
    resources :star_relationships
    resources :comments
  end

  resources :articles

  resources :charts, controller: 'people', as: 'people' do
    # resource :chart, :only => :show
    resources :palaces, controller: 'chart_palaces', as: 'chart_palaces', only: [:show], key: :foobax
  end
  
  get '/tong_shu/week/(:week)' => 'tong_shus#week_of', :as => 'tong_shu_week'
  get '/tong_shu/:year/:month' => 'tong_shus#index', :as => 'tong_shu_index'
  
  resources :feedback, controller: 'feedbacks', as: 'feedbacks'
  resources :tong_shus
  
  resources :stars, :only => [:index, :show] do
    resources :comments
  end
  
  resources :star_palaces do
    resources :comments
  end
  
  resources :branches, :only => [:index, :show] do
    resources :comments
  end
  
  resources :elements, :only => [:index, :show] do
    resources :comments
  end
  
  resources :stems_and_branches, controller: 'pillars', as: 'pillars', :only => [:index, :show] do
    resources :comments
  end
  
  resources :lunar_dates, only: [:show], format: :json
  
  resources :search, only: [:index, :create]
  
  resources :star_relationships do
    resources :comments
  end
  
  resources :palaces do
    resources :star_relationships do
      put :sort, on: :collection
    end
    get 'by_star/:star_id', :action => :show, :on => :member
  end
  
  namespace :admin do
    resources :members
  end

  devise_for :members
  
  devise_scope :member do
    get "sign_out", :to => "devise/sessions#destroy"
  end  
  
  resources :passwords, :only => [:edit, :update], controller: 'change_passwords'
  get '/change_password' => 'change_passwords#edit', :as => :change_password
  get '/updates' => 'articles#index', :as => :blog

  root :to => 'people#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
  
  def create
    palaces = {}
    stars = {}
    params.each do |name, val|
      if match = name.match(/palace_(\d+)/)
        palaces[match[1]] = val
      elsif match = name.match(/star_(\d+)/)
        stars[match[1]] = val
      end
    end
    
    query = []
    
    stars.each do |index, name|
      palace_id = palaces[index].to_i
      logger.info "#{name}: #{palace_id}"
      if palace_id == 12
        logger.info "I think palace should be 1"
        palace_id == 1
      else
        logger.info "drop it by 1"
        palace_id -= 1
      end
      star_column = name.gsub(/-/, '_')
      query << "(ming_id - #{star_column}_id) % 12 = #{palace_id}"
    end
    
    charts = Chart.where(query.join(' AND '))
    @people = current_member.people.where(chart_id: charts.map(&:id))
    
    logger.info query.join(' AND ').inspect
    logger.info palaces.inspect
    logger.info stars.inspect
    # @people = []
    respond_to do |format|
      format.html {
        if @people.empty?
          render action: 'index'
        end
      }
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form_partial.html.erb
<div class="search_form_partial" id="search_term_<%= n %>">
  Palace: <%= select_tag "palace_#{n}", options_for_select(Palace.all.collect{ |u| [u.name, u.id] })  %>
  Has star: <%= select_tag "star_#{n}", options_for_select(Star.all.collect{ |u| [u.full_name, u.to_param] })  %>
  <a href="#" data-delete="search_term_<%= n %>">(Remove)</a>
</div>

app/views/search/create.html.haml
%div{align: :center}
  %h1 Search Results

.charts
  %table.chart_list

    - @people.each do |person|
      %tr
        %td= person.first_name + " " + person.last_name 
        %td= " | " + person.dob.strftime('%Y %b %-d, %H:%M') 
        %td!= " | " + link_to("View Chart", person) + " | "
        %td= link_to("PDF", person_path(person, :format => :pdf)) + " | "
        %td= link_to('Change', edit_person_path(person)) + " | "
        %td= link_to('Delete', person, :confirm => 'Really?', :method => :delete)
  %br
  - if @people.empty?
    %div{align: :center}
      %div No one matches the search.
      %div
      %div So Sorry.

%div{align: :center}
  = link_to 'Search Again', search_index_path

%br/

app/views/search/index.html.erb
<div class="search">
  <h1>Search For Similar Charts</h1>
  <%= form_tag(:action => "create") do %>
    <div id="search_form">
      <input type="submit" />
      <%= render partial: 'form_partial', locals: {n: 0} %>
    </div>
    <a href="#" id="new_search_term">Add a search term</a>
    <script type="text/javascript">
      window.thePartial = '<%= escape_javascript(render partial: 'form_partial', locals: {n: 'XXX'}) %>';
    </script>
  <% end -%>
</div>