config/routes.rb
PolestarAstrology::Application.routes.draw do
  resources :star_groups
  
  resources :comments

  resources :chart_palaces do
    resources :star_relationships
    resources :comments
  end

  resources :articles

  resources :charts, controller: 'people', as: 'people' do
    # resource :chart, :only => :show
    resources :palaces, controller: 'chart_palaces', as: 'chart_palaces', only: [:show], key: :foobax
  end
  
  get '/tong_shu/week/(:week)' => 'tong_shus#week_of', :as => 'tong_shu_week'
  get '/tong_shu/:year/:month' => 'tong_shus#index', :as => 'tong_shu_index'
  
  resources :feedback, controller: 'feedbacks', as: 'feedbacks'
  resources :tong_shus
  
  resources :stars, :only => [:index, :show] do
    resources :comments
  end
  
  resources :star_palaces do
    resources :comments
  end
  
  resources :branches, :only => [:index, :show] do
    resources :comments
  end
  
  resources :elements, :only => [:index, :show] do
    resources :comments
  end
  
  resources :stems_and_branches, controller: 'pillars', as: 'pillars', :only => [:index, :show] do
    resources :comments
  end
  
  resources :lunar_dates, only: [:show], format: :json
  
  resources :search, only: [:index, :create]
  
  resources :star_relationships do
    resources :comments
  end
  
  resources :palaces do
    resources :star_relationships do
      put :sort, on: :collection
    end
    get 'by_star/:star_id', :action => :show, :on => :member
  end
  
  namespace :admin do
    resources :members
  end

  devise_for :members
  
  devise_scope :member do
    get "sign_out", :to => "devise/sessions#destroy"
  end  
  
  resources :passwords, :only => [:edit, :update], controller: 'change_passwords'
  get '/change_password' => 'change_passwords#edit', :as => :change_password
  get '/updates' => 'articles#index', :as => :blog

  root :to => 'people#index'

end

app/controllers/tong_shus_controller.rb
class TongShusController < ApplicationController
  respond_to :html, :json
  helper_method :hour_pillar

  def index
    start_date = DateTime.parse("#{params[:year]} #{params[:month]}")
    @month = Chart.find_or_create(start_date)
    @last_month = @month.solar_date - 1.month
    @next_month = @month.solar_date + 1.month
    end_date = start_date + 1.month - 1.day
    start_date -= start_date.wday
    end_date += (6-end_date.wday)%6
    @days = (start_date..end_date).map{|date| Chart.find_or_create(date)}
    
    @jieqi_dates = JieqiDate.where("start_date > ?", (@month.solar_date-1.month)).order(:start_date).limit(6)
    jieqi_array = []
    (0..(@jieqi_dates.size-2)).each do |i|
      jieqi_array << {id: @jieqi_dates[i].id,
          title: "#{@jieqi_dates[i].chinese} #{@jieqi_dates[i].english} Qi Node",
          start: @jieqi_dates[i].start_date.strftime("%Y-%m-%d"),
          end: (@jieqi_dates[i+1].start_date-1.day).strftime("%Y-%m-%d"),
          color: 'gray',
          type: 'jiqei'
        }
    end
    
    respond_with @days do |format|
      format.json {
        render :json => (jieqi_array + @days.map{|day|
          {
            id: day.id,
            title: day.day.name.titleize,
            start: day.solar_date.strftime("%Y-%m-%d"),
            url: tong_shu_week_path(day.solar_date.strftime("%Y-%b-%d")),
            color: 'green',
            type: 'day_stem_branch'
          }
        }).flatten
      }
    end
  end
  
  def week_of
    date = DateTime.parse(Time.parse(params[:week] ? params[:week] : '00:00').to_s)
    @days = date.get_week.map{|t| Chart.find_or_create t}
  end
  
  def hour_pillar(day_stem, hour_branch)
    stem = Stem.named [%w(jia yi bing ding wu ji geng xin ren kui jia yi),
    %w(bing ding wu ji geng xin ren kui jia yi bing ding),
    %w(wu ji geng xin ren kui jia yi bing ding wu ji),
    %w(geng xin ren kui jia yi bing ding wu ji geng xin),
    %w(ren kui jia yi bing ding wu ji geng xin ren kui)][(day_stem.ordinal-1)%5][hour_branch.ordinal-1]
    
    Pillar.find_by_stem_and_branch stem, hour_branch
  end
end


module DateTimeExtension
  def week_start
    @week_start ||= "Monday"
  end
  def week_start=(start)
    @week_start = start
  end
  def get_week
    start = clone
    start -= 1.day until start.strftime("%A")== week_start
    (0..6).map{|i| start + i.days}
  end
end

DateTime.send(:include, DateTimeExtension)

app/helpers/tong_shus_helper.rb
module TongShusHelper
end

app/views/tong_shus/index.html.haml
.tong_shu
  %h1 Tong Shu
  %p Here's a first shot at basic Tong Shu info.  I'll add more indicators as I can.  Click the Stem+Branch of each day to see the Stems and Branches of the hours.
  %h2 Year of the #{@month.year.name.titleize}
  .controls
    = link_to "<< #{@last_month.strftime("%B")}", tong_shu_index_path(@last_month.year, @last_month.strftime("%b").downcase)
    = link_to "#{@next_month.strftime("%B")} >>", tong_shu_index_path(@next_month.year, @next_month.strftime("%b").downcase)
  
  #calendar
  
  -# #jieqi

= content_for :head do
  = javascript_include_tag '/fullcalendar/fullcalendar.min'
  = stylesheet_link_tag '/fullcalendar/fullcalendar'
  
  :javascript
    $(document).ready(function() {
      $('#calendar').fullCalendar({
        editable: false,
        events: "/tong_shu/#{@month.solar_date.year}/#{@month.solar_date.strftime("%B")}.json",
        year: #{@month.solar_date.year},
        month: #{@month.solar_date.month-1},
        day: 1
      });
    });
	

app/views/tong_shus/week_of.html.haml
%h1 Week of #{@days.first.solar_date.strftime("%B %d, %Y")}
%p Click the links to view the chart for that hour.
%table
  %thead
    %tr
      %th &nbsp;
      - @days.each do |day|
        %th 
          #{day.solar_date.strftime "%A %d"}
          %br
          #{day.day.name.titleize}
  - Branch.all.each do |branch|
    %tr
      %td= branch.time_of_day
      - @days.each do |day|
        %td= link_to hour_pillar(day.day.stem, branch).name.titleize, person_path(day.solar_date.strftime("%Y-%B-%d+#{branch.hour}:00"))


    