config/routes.rb
PolestarAstrology::Application.routes.draw do
  resources :star_groups
  
  resources :comments

  resources :chart_palaces do
    resources :star_relationships
    resources :comments
  end

  resources :articles

  resources :charts, controller: 'people', as: 'people' do
    # resource :chart, :only => :show
    resources :palaces, controller: 'chart_palaces', as: 'chart_palaces', only: [:show], key: :foobax
  end
  
  get '/tong_shu/week/(:week)' => 'tong_shus#week_of', :as => 'tong_shu_week'
  get '/tong_shu/:year/:month' => 'tong_shus#index', :as => 'tong_shu_index'
  
  resources :feedback, controller: 'feedbacks', as: 'feedbacks'
  resources :tong_shus
  
  resources :stars, :only => [:index, :show] do
    resources :comments
  end
  
  resources :star_palaces do
    resources :comments
  end
  
  resources :branches, :only => [:index, :show] do
    resources :comments
  end
  
  resources :elements, :only => [:index, :show] do
    resources :comments
  end
  
  resources :stems_and_branches, controller: 'pillars', as: 'pillars', :only => [:index, :show] do
    resources :comments
  end
  
  resources :lunar_dates, only: [:show], format: :json
  
  resources :search, only: [:index, :create]
  
  resources :star_relationships do
    resources :comments
  end
  
  resources :palaces do
    resources :star_relationships do
      put :sort, on: :collection
    end
    get 'by_star/:star_id', :action => :show, :on => :member
  end
  
  namespace :admin do
    resources :members
  end

  devise_for :members
  
  devise_scope :member do
    get "sign_out", :to => "devise/sessions#destroy"
  end  
  
  resources :passwords, :only => [:edit, :update], controller: 'change_passwords'
  get '/change_password' => 'change_passwords#edit', :as => :change_password
  get '/updates' => 'articles#index', :as => :blog

  root :to => 'people#index'

end

app/models/chart_palace.rb
class ChartPalace < ActiveRecord::Base
  belongs_to :palace
  belongs_to :chart
  belongs_to :location, class_name: 'Branch'
  attr_accessor :stars
  
  after_initialize do |chart_palace|
    ming_location = chart.ming_id
    palace_id = chart_palace.palace_id

    chart_palace.stars = Star.all.select{|star|
      star_location = chart_palace.chart.send(star.symbol_name + "_id")
      (ming_location - star_location) % 12 == palace_id - 1
    }
  end
  
  # default_scope -> { order(palaces: :id)  }

  attr_reader :great_limit
  
  delegate :name, :ordinal, to: :palace
  
  def my_star_relationships(member, *including)
    return [] if stars.empty?
    
    all_relationships = StarRelationshipStar.where(member_id: member.id, palace_id: palace.id).map(&:star_relationship)

    all_relationships.select{|relationship|
      relationship.all.all?{|t| self.stars.include?(t.star)} && (
        relationship.any.empty? || relationship.any.any?{|t| self.stars.include?(t.star)}
      )
    }.select {|relationship|
      including.empty? || !(relationship.stars & including).empty?
    }
  end
  
  def great_limit(chart, person)
    clockwise = (person.yin_yang == chart.year.stem.yin_yang)
    great_limit_start = {'wood' => 3, 'fire' => 6, 'metal' => 4, 'water' => 2, 'earth' => 5}[chart.inner_element]
    if clockwise
      logger.info "* " * 40
      logger.info "Clockwise"
      logger.info "* " * 40
      decade_number = ordinal
    else
      logger.info "* " * 40
      logger.info "Anti - Clockwise"
      logger.info "* " * 40
      decade_number = (0..12).to_a[ordinal]
    end
    start = 10 * (decade_number - 1) + great_limit_start
    "#{start}-#{start+9}"
  end
  
  def small_limits(chart, person)
    branch = chart.year.branch
    if %w(horse dog tiger).include?(branch.animal)
      start = Branch.dragon
    elsif %W(monkey rat dragon).include?(branch.animal)
      start = Branch.dog
    else
      start = Branch.goat
    end
    
    # if person.yin_yang == 'yang'
      
    
    start_num = (12 + ordinal-start.ordinal)%12+1
    (0..7).map{|i| start_num + 12*i}.map(&:to_s).join(" ")
    
  end
  
  # def stars
  #   @stars ||= []
  # end
  # 
  # def stars=(arr)
  #   @stars = SortedStarList.new(arr)
  # end
  
  def major_stars
    SortedStarList.new stars.select{|t| t.rank <= 4}
  end
  
  def minor_stars
    SortedStarList.new stars.select{|t| t.rank > 4}
  end
  
  class SortedStarList < Array
    def sort_by_rank
      sort{|x,y| 
        if x.rank == y.rank
          x.id <=> y.id
        else
          x.rank <=> y.rank
        end
      }
    end
  end
end

app/controllers/chart_palaces_controller.rb
class ChartPalacesController < ApplicationController
  respond_to :js, :html
  def show
    @person = Person.find(params[:person_id])
    @chart = @person.chart
    @palace = Palace.find(params[:id])
    @chart_palace = @chart.palaces.by_palace(@palace)
    
    @star_relationships = @chart_palace.my_star_relationships(current_member)
    
    respond_with(@chart_palace)
  end
end

app/helpers/chart_palaces_helper.rb
module ChartPalacesHelper
  def star_relationship_string(star_relationship)
    val = star_names(star_relationship.all).to_english_list
    unless star_relationship.any.empty?
      val += ", with " + star_names(star_relationship.all).to_english_list('or')
    end
    val += " in the #{star_relationship.palace.name} Palace"
  end
  
  def star_names(star_relationship_stars)
    star_relationship_stars.map{|s| s.star.pinyin}
  end
end

app/views/chart_palaces/_chart_box.html.haml
= render chart_box.location, locals: {chart_palace: chart_box}

app/views/chart_palaces/_chart_palace.html.haml
.star_relationship_container
  .controls
    = link_to new_chart_palace_star_relationship_path(chart_palace), data: {remote: true, placement: 'bottom'}, rel: 'tooltip', title: 'Add Star Info' do
      %i.icon-plus
    %a(href='#' class='show_all_relationship_data' rel="tooltip" title="Show All Info" data-placement="bottom")
      %i.icon-chevron-down
    %a(href='#' class='collapse_all_relationship_data' rel="tooltip" title="Hide All Info" data-placement="bottom")
      %i.icon-chevron-up
  %h1= chart_palace.palace.name
  - relationships = chart_palace.my_star_relationships(current_member).each do |star_relationship|
    %h5
      = star_relationship_string(star_relationship)
      %a(data-toggle="collapse" data-target="#star_relationship_#{star_relationship.id}")
        %i.icon-chevron-down.collapsed
      
    .collapse.in[star_relationship]
      - star_relationship.comments.each do |comment|
        .comment.clickable.star_relationship_comment(id="comment_#{comment.id}" data-id="#{comment.id}")
          != RedCloth.new(comment.comments).to_html
  - if relationships.empty?
    %h4 You have not entered any information that relates to the #{chart_palace.palace.name} Palace in this chart

app/views/chart_palaces/_modal.html.erb
<div class="modal hide fade <%= chart_palace.palace.to_param %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>The <%= chart_palace.palace.name %> Palace</h3>
  </div>
  <div class="modal-body">
    <% relationships = chart_palace.my_star_relationships(current_member).each do |star_relationship| %>
      <h5><%= star_relationship_string(star_relationship) %></h5>
      <% star_relationship.comments.each do |comment| %>
        <div class="star_relationship_comments"><%= raw(RedCloth.new(comment.comments).to_html) %></div>
      <% end %>
    <% end %>
    
    <% if relationships.empty? %>
      <h4>You have not entered any information that relates to the <%= chart_palace.palace.name %> Palace in this chart</h4>
    <% end %>
    <%= link_to 'Add Star Info', new_palace_star_relationship_path(chart_palace.palace), target: '_blank' %>
    
  </div>
  <div class="modal-footer">
    <button class="btn close" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/chart_palaces/_show_modal.html.haml
%h1 The #{palace.name} Palace in #{person.full_name}'s Chart

= render chart_palace

- star_relationships.each do |star_relationship|
  %h5= star_relationship_string(star_relationship)
  - star_relationship.comments.each do |comment|
    .star_relationship_comments!= RedCloth.new(comment.comments).to_html
    
:textile
  <!-- start slipsum code -->

  Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.

  Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.

  Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.

  <!-- please do not remove this line -->

  <div style="display:none;">
  <a href="http://slipsum.com">lorem ipsum</a></div>

  <!-- end slipsum code -->
  

app/views/chart_palaces/show.html.haml
= render partial: 'show'

app/views/chart_palaces/show.js.erb
'<%= escape_javascript(render(partial: 'show')) %>'